ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~shadowadept/items/c0saleat.baf~
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~shadowadept/items/c0saleat.baf~
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~shadowadept/items/c0saleat.baf~
END

COPY ~shadowadept/items/C0SALEAT.BAM~ ~override~
COPY ~shadowadept/Items/C0SALEA1.itm~ ~override/C0SALEA1.itm~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0SADEPT~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Dark Leather~
SAY NAME2 ~Dark Leather~
SAY DESC ~This armor is worn by shadow adepts and is designed not to interfere with casting and move freely through the Plane of Shadow. 

Equipped Abilities:
- Spellcasting is not disabled

STATISTICS:

Armor Class: 8 (10 vs. piercing and missile)
Requires:
 4 Strength

Weight: 15~

COPY ~shadowadept/Items/C0SALEA2.itm~ ~override/C0SALEA2.itm~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0SADEPT~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Dark Leather +1~
SAY NAME2 ~Dark Leather +1~
SAY DESC ~This armor is worn by shadow adepts and is designed not to interfere with casting and move freely through the Plane of Shadow. 

Equipped Abilities:
- +1 to saves vs. death
- Spellcasting is not disabled

STATISTICS:

Armor Class: 7 (9 vs. piercing and missile)
Requires:
 4 Strength

Weight: 15~

COPY ~shadowadept/Items/C0SALEA3.itm~ ~override/C0SALEA3.itm~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0SADEPT~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Dark Leather +2~
SAY NAME2 ~Dark Leather +2~
SAY DESC ~This armor is worn by shadow adepts and is designed not to interfere with casting and move freely through the Plane of Shadow. 

Equipped Abilities:
- +2 to saves vs. death
- Spellcasting is not disabled

STATISTICS:

Armor Class: 6 (8 vs. piercing and missile)
Requires:
 4 Strength

Weight: 15~

COPY ~shadowadept/Items/C0SALEA4.itm~ ~override/C0SALEA4.itm~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0SADEPT~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Dark Leather +3~
SAY NAME2 ~Dark Leather +3~
SAY DESC ~This armor is worn by shadow adepts and is designed not to interfere with casting and move freely through the Plane of Shadow. 

Equipped Abilities:
- +3 to saves vs. death
- Spellcasting is not disabled

STATISTICS:

Armor Class: 5 (7 vs. piercing and missile)
Requires:
 4 Strength

Weight: 15~

COPY ~shadowadept/Items/C0SALEA5.itm~ ~override/C0SALEA5.itm~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0SADEPT~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Dark Leather +4~
SAY NAME2 ~Dark Leather +4~
SAY DESC ~This armor is worn by shadow adepts and is designed not to interfere with casting and move freely through the Plane of Shadow. 

Equipped Abilities:
- +4 to saves vs. death
- Spellcasting is not disabled

STATISTICS:

Armor Class: 4 (6 vs. piercing and missile)
Requires:
 4 Strength

Weight: 15~

COPY ~shadowadept/Items/C0SALEA6.itm~ ~override/C0SALEA6.itm~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0SADEPT~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Dark Leather +5~
SAY NAME2 ~Dark Leather +5~
SAY DESC ~This armor is worn by shadow adepts and is designed not to interfere with casting and move freely through the Plane of Shadow. 

Equipped Abilities:
- +5 to saves vs. death
- Spellcasting is not disabled

STATISTICS:

Armor Class: 3 (5 vs. piercing and missile)
Requires:
 4 Strength

Weight: 15~

COPY ~shadowadept/Items/C0SALEA7.itm~ ~override/C0SALEA7.itm~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = (IDS_OF_SYMBOL (~kit~ ~C0SADEPT~))
	  parameter2 = 9
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Dark Leather +6~
SAY NAME2 ~Dark Leather +6~
SAY DESC ~This armor is worn by shadow adepts and is designed not to interfere with casting and move freely through the Plane of Shadow. 

Equipped Abilities:
- +6 to saves vs. death
- Immunity to time stop
- Spellcasting is not disabled

STATISTICS:

Armor Class: 2 (4 vs. piercing and missile)
Requires:
 4 Strength

Weight: 15~

COPY ~shadowadept/Items/c0nring.bam~ ~override/c0nring.bam~
COPY ~shadowadept/Items/c0nring.itm~ ~override/c0nring.itm~
SAY NAME1 ~Ring of Shadows~
SAY NAME2 ~Ring of Shadows~
SAY DESC ~This translucent ring has been in <CHARNAME>'s possession for as long as <PRO_HESHE> can remember, and while it appears to lack magical properties, it seems to be special in some way regardless.

STATISTICS:
Weight: 0~