COPY ~%MOD_FOLDER%/2da~ ~override~
COPY ~%MOD_FOLDER%/audio~ ~override~
COPY ~%MOD_FOLDER%/animations~ ~override~
COPY ~%MOD_FOLDER%/portraits~ ~override~
COPY ~%MOD_FOLDER%/spells~ ~override~
COPY ~%MOD_FOLDER%/spells/bams~ ~override~

////////////////////////////////////////
///////////////ANIMATIONS///////////////
////////////////////////////////////////

INCLUDE ~%MOD_FOLDER%/lib/animations.tpa~

//AUDIO

LAF HANDLE_AUDIO END

////////////////////////////////////////////
//////////////////SPELLS////////////////////
////////////////////////////////////////////

INCLUDE ~%MOD_FOLDER%/lib/shadow_magic.tpa~

ACTION_IF MOD_IS_INSTALLED ~SETUP-RR.TP2~ ~6~ THEN BEGIN
COPY ~%MOD_FOLDER%/2DA/OTHER/C0SABARD-RR.2DA~ ~OVERRIDE/C0SABARD.2DA~
END

ACTION_IF MOD_IS_INSTALLED ~SETUP-CDTWEAKS.TP2~ ~2270~ THEN BEGIN
COPY ~%MOD_FOLDER%/2DA/OTHER/C0SABARD-CD.2DA~ ~OVERRIDE/C0SABARD.2DA~
END

////////////////////////////////////////////
///////////////////KIT//////////////////////
////////////////////////////////////////////

INCLUDE ~%MOD_FOLDER%/lib/kit.tpa~

////////////////////////////////////////
/////////DIALOGUE///////////////////////
////////////////////////////////////////

COMPILE ~%MOD_FOLDER%/dialogue/c0satalk.d~
COMPILE ~%MOD_FOLDER%/dialogue/c0saorb.d~

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN
COMPILE ~%MOD_FOLDER%/dialogue/bg2dial.d~
END

////////////////////////////////////////
/////////IWDEE-IDS PATCH////////////////
////////////////////////////////////////

ACTION_IF GAME_IS ~IWDEE~ THEN BEGIN
INCLUDE ~%MOD_FOLDER%/lib/ids_iwdee.tpa~
END

////////////////////////////////////////
/////////SCRIPTS////////////////////////
////////////////////////////////////////

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/scripts/baldur.baf~
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/scripts/bdbaldur.baf~
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/scripts/baldur.baf~
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdcutgl2.bcs~ THEN BEGIN
COMPILE ~%MOD_FOLDER%/dialogue/soddial.d~
COMPILE ~%MOD_FOLDER%/scripts/c0cutgl2.baf~
END

COMPILE ~%MOD_FOLDER%/scripts/c0saplay.baf~
EXTEND_BOTTOM ~dplayer2.bcs~ ~%MOD_FOLDER%/scripts/c0saplay.baf~

COMPILE ~%MOD_FOLDER%/scripts/c0saorb.baf~
COMPILE ~%MOD_FOLDER%/scripts/c0sasumm.baf~
COMPILE ~%MOD_FOLDER%/scripts/c0devsha.baf~
COMPILE ~%MOD_FOLDER%/scripts/c0nighth.baf~
COMPILE ~%MOD_FOLDER%/scripts/c0sa711.baf~

COPY_EXISTING ~c0sadep.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
	  match_opcode = 72
	  parameter1 = IDS_OF_SYMBOL (~SPECIFIC~ ~SHADOW_ADEPT~)
  END

COPY ~%MOD_FOLDER%/Items/c0sabook.bam~ ~override~
COPY ~%MOD_FOLDER%/Items/c0sabook.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = IDS_OF_SYMBOL (~SPECIFIC~ ~SHADOW_ADEPT~)
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (@1)
END
SAY NAME1 ~Book~
SAY NAME2 ~Shadow Tome of Shar~
SAY DESC ~This black leather-bound tome is filled with magical runes and incantations that seem to shift and change slightly as you blink.

STATISTICS:

- Learns all Shadow Weave spells on use.

Weight: 2~

COMPILE ~%MOD_FOLDER%/dialogue/c0sabook.d~

OUTER_SET readtome = RESOLVE_STR_REF (~Read Tome~)
APPEND ~ITEMDIAL.2da~ ~C0SABOOK    %readtome%    C0SABOOK~

COPY ~%MOD_FOLDER%/Items/c0saorb.bam~ ~override~
COPY ~%MOD_FOLDER%/Items/c0saorbc.bam~ ~override~
COPY ~%MOD_FOLDER%/Items/c0saorb.itm~ ~override~
SAY NAME1 ~Black Orb~
SAY NAME2 ~Shadow Orb~
SAY DESC ~This smoky glass sphere emanates an aura of power unlike any magic you're familiar with. A strange energy struggles to break free of it.~

OUTER_SET useorb = RESOLVE_STR_REF (~Activate~)
APPEND ~ITEMDIAL.2da~ ~C0SAORB    %useorb%    C0SAORB~

INCLUDE ~%MOD_FOLDER%/lib/familiars.tpa~

///////////////////////////
///////////ITEMS///////////
///////////////////////////

INCLUDE ~%MOD_FOLDER%/lib/item_pack.tpa~

///////////////////////////
/////////CROSSMOD//////////
///////////////////////////

// Shadow Magic

ACTION_IF FILE_EXISTS_IN_GAME ~L#Fou.cre~ AND FILE_EXISTS_IN_GAME ~L#Fou25.cre~
THEN BEGIN
  PRINT ~Adding crossmod compatibility between Foundling and Shadow Magic~
  COMPILE ~%MOD_FOLDER%/dialogue/npc/foundling.d~
COPY_EXISTING ~L#Fou.cre~ ~override~
  WRITE_BYTE 0x274 (IDS_OF_SYMBOL (~SPECIFIC~ ~SHADOW_ADEPT~))
COPY_EXISTING ~L#Fou25.cre~ ~override~
  WRITE_BYTE 0x274 (IDS_OF_SYMBOL (~SPECIFIC~ ~SHADOW_ADEPT~))
END