COPY ~%MOD_FOLDER%/itempack/bams~ ~override~

// PVRZ-based bams

ACTION_FOR_EACH bamFile IN ~c0samasc.bam~ BEGIN
    COPY ~%MOD_FOLDER%/itempack/bams/%bamFile%~ ~override~
      LPF UPDATE_PVRZ_INDICES RET original_base_index new_base_index END
    ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
      LAF INSTALL_PVRZ
      INT_VAR
        original_base_index = original_base_index
        new_base_index = new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/pvrz/mos%original_base_index%.pvrz~
      END
    END
END

////////////////////////////////////////
/////////ITEMS//////////////////////////
////////////////////////////////////////

// Ring of Black Light

COPY ~%MOD_FOLDER%/itempack/c0sarng1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Ring~
SAY NAME2 ~Ring of Black Light~
SAY DESC ~This black glass ring feels heavy and unnatural in your hands. When worn by those profiicent in shadow magic, it bolsters their ability to resist the life-draining nature of the Shadow Weave.

STATISTICS:
– Constitution: +1
– Save vs. Death: +4

Weight: 0~

ACTION_IF FILE_EXISTS_IN_GAME ~ar0602.bcs~ THEN BEGIN
EXTEND_TOP ~ar0602.bcs~ ~%MOD_FOLDER%/scripts/ar0602.baf~
END

// Dark Dreamer +2

APPEND ~splprot.2da~ ~C0SAS2H1%TAB%0x111%TAB%0x00000001%TAB%8~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0SAS2H1~ BEGIN
	    SET C0SAS2H1 = %row%
	  END
	END

COPY ~%MOD_FOLDER%/itempack/c0sas2h1.spl~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sas2h1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Fighter / Shadow Adept
Fighter / Shadow Adept / Thief
Nightsinger~)
END
LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 326
      match_parameter2 = 0
	  parameter2 = %C0SAS2H1%
END
SAY NAME1 ~Two-handed Sword~
SAY NAME2 ~Dark Dreamer +2~
SAY UNIDENTIFIED_DESC ~The two-handed sword is a derivative of the long sword. Weaponsmiths have always looked for ways to improve existing weapons, and in an effort to improve the long sword, the blade was lengthened. Eventually, the handle had to be extended and two hands became necessary to properly swing the sword. The primary function of two-handed swords is cleaving mounted knights and breaking up pike formations.

STATISTICS:

Damage: 2D6
Damage type: slashing
Weight: 8
Speed Factor: 10
Proficiency Type: Two-Handed Sword
Type: 2-handed
Requires: 14 Strength~
SAY DESC ~This dark steel two-handed sword appears to be nothing more than a well-balanced weapon in the hands of a regular warrior, but when wielded by a user of Shadow Magic it seems to come to life. Its blade has the ability to compel anyone cut to fall into a magically induced sleep, then hungrily devours the victim's dreams to restore the wielder's memory. The holy symbol in the sword's pommel suggests that it once belonged to followers of Shar, goddess of night and loss.

STATISTICS:

Combat Effects:
– 20% chance that hit target must save vs. spells at +3 or be put to sleep for 2 rounds
– Dream Eater: Attacks against sleeping targets deal 1d10 magic damage and restore one of the wielder's lost spells of up to 4th level

Equipped Effects:
– Saves vs. Enchantment: +3
– Hit Points: -10

THAC0: +2
Damage: 1d10+2, +1 magic damage
Damage type: slashing
Speed Factor: 8
Proficiency Type: Two-handed Sword
Type: Two-handed
Requires:
 14 Strength

Weight: 10~

ACTION_IF FILE_EXISTS_IN_GAME ~bdziatar.cre~ THEN BEGIN
COPY_EXISTING ~bdziatar.cre~ ~override~
REMOVE_CRE_ITEM ~sw2h02~
ADD_CRE_ITEM ~c0sas2h1~ #0 #0 #0 ~NONE~ ~weapon1~
END

COPY ~%MOD_FOLDER%/itempack/c0saamu1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Amulet~
SAY NAME2 ~Shadow Phylactery~
SAY DESC ~The purple stone in this amulet draws upon and contains a limited amount of energy from the Shadow Weave. When a user of Shadow Magic summons the power of the Shadow Weave, the amulet is used as a medium for channelling the energy required, allowing the shadow adept to cast lower level spells without risking their own life force. However, a constant amount of vitality is required to sustain the amulet's power as long as it is worn.

STATISTICS:

Equipped Effects:
– Hit Points: -15
– Can memorize one extra wizard spell of 1st to 4th level
– Protects the wearer against Constitution loss from using 1st–4th level Shadow Weave spells

Weight: 1~

COPY ~%MOD_FOLDER%/itempack/c0saamu2.itm~ ~override~
SAY NAME1 ~Amulet~
SAY NAME2 ~Shadovar Amulet~
SAY DESC ~This amulet appears old yet carries a powerful magical enchantment. The symbol of the Shade Enclave, an ancient city of the Shadovar, is printed on the back of the triangular-shaped pendant.

STATISTICS:

Equipped Effects:
– Casting Speed: +2 (Shadow Adepts), +1 (Others)

Weight: 1~

ACTION_IF FILE_EXISTS_IN_GAME ~shadel.cre~ THEN BEGIN
COPY_EXISTING ~shadel.cre~ ~override~
ADD_CRE_ITEM ~c0saamu1~ #0 #0 #0 ~NONE~ ~inv~
END

COPY ~%MOD_FOLDER%/itempack/c0sarob1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Mage Robes~
SAY NAME2 ~Shrouded Robes~
SAY UNIDENTIFIED_DESC ~Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class mages may wear these enchanted robes.~
SAY DESC ~These black robes are made of some sort of unusually light material and bear enchantments that empower the magic used by shadow adepts.

STATISTICS:

Equipped Effects:
– All cold and magic damage inflicted by the wearer is increased by 15%
– Spell Duration: +10%
– Hit Points: -10
– Cold Resistance: +50%
– Fire Resistance: -25%

Weight: 1~

ACTION_IF FILE_EXISTS_IN_GAME ~lavok2.cre~ THEN BEGIN
COPY_EXISTING ~lavok2.cre~ ~override~
ADD_CRE_ITEM ~c0sarob1~ #0 #0 #0 ~NONE~ ~inv~
END

COPY ~%MOD_FOLDER%/itempack/c0sasta1.spl~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sasta1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Quarterstaff~
SAY NAME2 ~Staff of Starless Nights~
SAY UNIDENTIFIED_DESC ~The simplest and humblest of staff weapons, the quarterstaff is a length of wood ranging six to nine feet in length. High quality quarterstaves are made of stout oak and are shod with metal at both ends. The quarterstaff must be wielded with both hands.~
SAY DESC ~This powerful wizard's staff was created by Acthelion, a archmage and favored priest of Shar. It was said to have always been in his hand during his lifetime, and its separation from him is taken to be a likely sign of his death, though some claim that he ascended to some other plane and left behind all his possessions, including this one. Others believe he may still be seeking it...

When the night holds dominance over the Prime Material Plane, the black gem on the tip of the staff seems to glow, and its power is greater.

STATISTICS:

Charge abilities:
– Shadow Shield once per day
– Fireshield (Shadow) once per day
– Negative Energy Burst once per day (centered on self)

Combat abilities:
– 25% chance to cast Drain Vitality on successful hit

Equipped abilities:
– Casting Level: +2 (+4 during nighttime)
– Magic Resistance: +10% (20% during nighttime)
– Magic Damage Resistance: +20% (40% during nighttime)

THAC0: +5 bonus, strikes as a +5 weapon
Damage: 1D6 + 1, +1d6+3 magic damage
Damage type: crushing
Speed Factor: 4
Proficiency Type: Quarterstaff
Type: 2-handed
Requires: 5 Strength

Weight: 4~

ACTION_IF FILE_EXISTS_IN_GAME ~ribald3.sto~ THEN BEGIN
COPY_EXISTING ~ribald3.sto~ ~override~
ADD_STORE_ITEM ~c0sasta1~ #0 #0 #0 ~IDENTIFIED~ #6
END

ADD_PROJECTILE ~%MOD_FOLDER%/itempack/c0sadagg.pro~
COPY ~%MOD_FOLDER%/itempack/c0sadag1.spl~ ~override~
SAY NAME1 ~Blinding Darkness~
SAY NAME2 ~Blinding Darkness~
COPY ~%MOD_FOLDER%/itempack/c0sadag1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Dagger~
SAY NAME2 ~Night Cutter +2~
SAY UNIDENTIFIED_DESC ~The typical dagger has a pointed, double-edged blade, as opposed to a knife, which has a single edge and is a bit shorter.

STATISTICS:

Damage: 1D4
Damage type: piercing
Weight: 1
Speed Factor: 1
Proficiency Type: Dagger
Type: 1-handed
Requires: 3 Strength~
SAY DESC ~This wicked knife seems to suck in light around it rather than reflecting it. Only a wielder familiar with Shadow Magic may draw upon its powers.

STATISTICS:

Combat abilities:
– Returns to the wielder's hand when thrown
– When thrown, there is a 10% chance that the wielder will be teleported into melee range of the target and turn invisible for five rounds.
– On a successful backstab, casts Blinding Darkness on target and restores one 1st level spell to the wielder's memory.

Equipped abilities:
– Hit Points: -5

THAC0: +2
Damage: 1d4+1, +1 magic (melee only)
Damage type: Piercing or missile
Speed Factor: 1
Proficiency Type: Dagger
Type: One-handed
Requires:
 3 Strength

Weight: 1~
WRITE_SHORT 0x9C ~%c0sadagg%~

COPY ~%MOD_FOLDER%/itempack/c0sas1h1.spl~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sas1h1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Fighter / Shadow Adept
Shadow Adept / Thief
Fighter / Shadow Adept / Thief
Nightsinger~)
END
SAY NAME1 ~Long Sword~
SAY NAME2 ~Edge of Eclipse +4~
SAY UNIDENTIFIED_DESC ~These swords are usually referred to as doubled-edged swords, war swords, or military swords. In many cases, the long sword has a single-edged blade. There is no single version of the long sword; the design and length vary from culture to culture, and may vary within the same culture depending on the era. Among the most common characteristics of all long swords is their length, which ranges from 35 to 47 inches. In the latter case, the blade is known to take up 40 inches of the total length. Most long swords have a double-edged blade and a sharp point at the tip. Despite the tip, the long sword is designed for slashing, not thrusting.

STATISTICS:

Damage: 1D8
Damage type: slashing
Weight: 4
Speed Factor: 5
Proficiency Type: Long Sword
Type: 1-handed
Requires: 6 Strength~
SAY DESC ~This blade is made out of some unusual black metal which, instead of bearing a reflective sheen, is dotted with sparkles of light that resemble stars in the night sky. When a wielder of Shadow Magic draws the blade, they feel empowered, gaining a strange desire to drain the life out of their opponents. The edge of the blade is sharp and cuts through steel as if it were paper.

STATISTICS:

Combat abilities:
– On a critical hit, drains ten hit points and one point of Strength (1 turn) from the target and transfers them to the wielder.
– Reduces target's armor class by one point for 2 rounds on successful hit

Equipped abilities:
– Strength: +1
– Critical Hit Chance: +10% (this weapon only)
– Hit Points: -10

THAC0: +4
Damage: 1d8+4 (slashing)
Speed Factor: 2
Proficiency Type: Long Sword
Type: One-handed
Requires:
 6 Strength

Weight: 2~

ACTION_IF FILE_EXISTS_IN_GAME ~uddrow23.sto~ THEN BEGIN
COPY_EXISTING ~uddrow23.sto~ ~override~
ADD_STORE_ITEM ~c0sas1h1~ #0 #0 #0 ~IDENTIFIED~ #6
END

COPY ~%MOD_FOLDER%/itempack/c0sapot1.spl~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sapot1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Potion~
SAY NAME2 ~Shar's Infusion~
SAY UNIDENTIFIED_DESC ~Potions are typically found in ceramic, crystal, glass, or metal flasks or vials. Flasks or other containers generally contain enough fluid to provide one person with one complete dose to achieve the effects of the potion.

STATISTICS:

Weight: 1~
SAY DESC ~This bottle contains a mysterious black-colored liquid which gives off a shadowy smoke when the bottle is unstoppered.

STATISTICS:

Special: Protects from Constitution loss by casting Shadow Weave spells
Duration: 1 turn

Weight: 1~

COPY ~%MOD_FOLDER%/itempack/c0bstar1.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0bstar2.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0bstar3.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0bstar1.spl~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sadar1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Dart~
SAY NAME2 ~The Black Star +2~
SAY UNIDENTIFIED_DESC ~The dart is a small, easily concealable missile weapon that is thrown, rather than fired from a launcher.

STATISTICS:

Damage: 1D3
Damage type: missile
Weight: 0
Speed Factor: 2
Proficiency Type: Dart
Type: 1-handed~
SAY DESC ~This tiny black dart was enchanted using magic from the Shadow Weave. As a result, it is innately opposed to Mystra's Weave and is significantly more effective when used against practitioners of arcane magic, tearing away spells from their memory.

STATISTICS:

Combat abilities:
– Returns to the wielder's hand when thrown
– Mages and bards must save vs. spell or suffer 1d4 magic damage and lose one memorized spell

THAC0: +2, +4 vs. mages and bards
Damage: 1d3+2, +4 vs. mages and bards
Damage type: missile
Speed Factor: 0
Proficiency Type: Dart
Type: One-handed

Weight: 0~

COPY ~%MOD_FOLDER%/itempack/c0sarng2.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sarn2a.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sarn2b.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sarng2.itm~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 177 // display string
      match_parameter1 = 0
 parameter1 = 12
 parameter2 = 6
  END
SAY NAME1 ~Ring~
SAY NAME2 ~Ring of Shadowkin~
SAY DESC ~This ring appears to be made of a smoky-grey material with a surface which is constantly shifting with movements that resemble flowing water. When worn, the wearer becomes partially translucent, resembling a shadow.

STATISTICS:

Charge abilities:
– Charm Spectral Undead for 5 turns three times per day (Save vs. Spell negates)

Equipped abilities:
– Armor Class: +1, +3 vs. spectral undead
– Saving Throws: +1, +3 vs. spectral undead
– Charisma: +1 (Shadow Adepts)

Weight: 0~

ACTION_IF FILE_EXISTS_IN_GAME ~bdshkorl.cre~ THEN BEGIN
COPY_EXISTING ~bdshkorl.cre~ ~override~
ADD_CRE_ITEM ~c0sarng2~ #0 #0 #0 ~NONE~ ~inv~
END

COPY ~%MOD_FOLDER%/itempack/c0saclc1.itm~ ~override~
SAY NAME1 ~Cloak~
SAY NAME2 ~Mantle of Dark Mists~
SAY UNIDENTIFIED_DESC ~The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.~
SAY DESC ~This cloak seems to constantly expel a thin black mist, which upon uttering the correct command word is expelled into a thick fog that blinds all within it. In addition, the cloak seems to be enchanted to repel certain types of magic and mask the wearer's presence from any form of spectral undead.

STATISTICS:

Charge abilities:
– Black Mist once per day centered on self

Equipped abilities:
– Wearer is ignored by shadows, wraiths and other incorporeal undead
– Save vs. Illusion: +2
– Save vs. Necromancy: +2
– Save vs. Alteration: +2

Weight: 1~

ACTION_IF FILE_EXISTS_IN_GAME ~bd0115.bcs~ THEN BEGIN
EXTEND_TOP ~bd0115.bcs~ ~%MOD_FOLDER%/scripts/bd0115.baf~
END

COPY ~%MOD_FOLDER%/itempack/c0sas1h2.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sas1h2.spl~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sas1h2.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Fighter / Shadow Adept
Fighter / Shadow Adept / Thief
Nightsinger~)
END
SAY NAME1 ~Bastard Sword~
SAY NAME2 ~Dreadflame +5~
SAY UNIDENTIFIED_DESC ~Also known as the hand-and-a-half sword, the bastard sword derives its name from the fact that it is halfway between the two-handed sword and the long sword. The bastard sword has a double-edged blade and a long grip, which can accommodate both hands if preferred. The overall length of the bastard sword ranges between four feet and four feet ten inches.

STATISTICS:

Damage: 1D10
Damage type: slashing
Weight: 6
Speed Factor: 7
Proficiency Type: Bastard Sword
Type: 1-handed
Requires: 11 Strength~
SAY DESC ~Kryn Darkflame discovered this powerful sword during one of his many ventures into the dangerous Plane of Shadow. Its blade constantly releases purple flames that run cold rather than hot, allowing it to be sheathed. By some strange magic, its flames only burn when the victim is made to feel fear. When commanded, the flames can be manipulated to create a protective wall around the wielder.

The weapon seems innately opposed to creatures of good and light and deals greater harm when cutting such beings.

STATISTICS:

Charge abilities:
– Fireshield (Shadow) three times per day
  Special: Any who strike the user within a 5-ft. radius suffers 1d6+2 cold damage and suffer a -1 penalty to THAC0 and armor class for 6 rounds
  Duration: 1 turn
  Area of Effect: The user

Equipped abilities:
– Immunity to fear and morale failure
– Wielder regenerates 1 hit point per round
– Hit Points: -20

Combat abilities:
– Deals 3d6 points of magic damage to good-aligned creatures
– 20% per hit to cause target to run in panic for 5 rounds on a failed Save vs. Spell. Deals 1d6 fire damage to panicked targets.
– On a critical hit, cast Blackfire Fury on target (10d10 unmitigated fire damage, target is raised as a devil shade allied with the wielder if slain. Save vs. Spell at -4 for half damage)

THAC0: +5
Damage: 2d4+5, 1d6 cold damage
Damage type: slashing
Speed Factor: 3
Proficiency Type: Bastard Sword
Type: One-handed
Requires:
 11 Strength

Weight: 7~

COPY ~%MOD_FOLDER%/itempack/c0sas1h3.itm~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
      match_parameter1 = 0
 parameter1 = RESOLVE_STR_REF (~Two Levels Drained~)
  END
SAY NAME1 ~Scimitar~
SAY NAME2 ~Soulbane +4~
SAY UNIDENTIFIED_DESC ~The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The "shamshir," as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 5
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 4~
SAY DESC ~This scimitar was the signature weapon of Septimus Victus, a Shadovar warrior. Its wicked edge is complemented by life-draining magic that permanently weakens anyone it cuts.

STATISTICS:

Combat abilities:
– Each hit reduces target's save vs. death modifier by one point for five turns
– Each hit drains two levels on a failed save vs. death at -2

Equipped abilities:
– Magic Resistance: +25%

THAC0: +4
Damage: 1d8+6, +2 magic
Damage type: slashing
Speed Factor: 1
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 1~

COPY ~%MOD_FOLDER%/itempack/c0sas1h4.spl~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sas1h4.itm~ ~override~
SAY NAME1 ~Katana~
SAY NAME2 ~Weaveshear +2~
SAY UNIDENTIFIED_DESC ~The katana is a single-edged, slightly curved sword that ends with a chisel point. The katana is perhaps one of the finest swords ever made, the steps to its creation a long and secret process that is more art form than anything else. This blade is an important facet of Kara-Turan culture. To touch or wield a samurai's katana is to insult the samurai and to incite his wrath. For a gaijin, or foreigner, to own such a blade is a rare occurrence. Either the gaijin is a greatly honored friend of an important minister, or the gaijin has murdered a samurai.

STATISTICS:

Damage: 1d10 (slashing)
Speed Factor: 4
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 6~
SAY DESC ~This blade was the signature weapon of the ogre mage Shadruk, who by all accounts forged it from a wound in the Weave. Whether such a thing is true is debatable, but the blade's disruptive powers lend some credibility to the claim.

STATISTICS:

Combat abilities:
– Each hit inflicts a cumulative 5% chance of spell failure (no save)
– On a critical hit, drain two wizard spells of up to 6th level and restores two of the wielder's wizard spells

Equipped abilities:
– Magic Resistance: +5%

THAC0: +2
Damage: 1d10+2 (slashing)
Speed Factor: 2
Proficiency Type: Katana
Type: One-handed
Requires:
 6 Strength

Weight: 4~

COPY ~%MOD_FOLDER%/itempack/c0sawand.spl~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sawan1.itm~ ~override~
SAY NAME1 ~Wand~
SAY NAME2 ~Wand of Negative Energy~
SAY UNIDENTIFIED_DESC ~Wands are 1 1/4 feet long and slender. They are made of ivory, bone, or wood and are usually tipped with something – metal, crystal, stone, etc. They are fragile and tend to break easily. Because of this, they are often kept in cases. Wands generally store one or more magical effects powered by charges, each use costing one or more charges (depending in the item). When a wand runs out of charges, it is consumed and destroyed.~
SAY DESC ~This wand was created using Shadow Magic and, unlike other items enchanted by the same source, may be used by any user of arcane magic. When used, this wand launches a thin red ray of negative energy which weakens its target.

As this wand draws power from the Shadow Weave, anyone aside from a shadow adept who attempts to use this wand will suffer 1d10 magic damage.

STATISTICS:

Charge abilities:
– Negative Energy Ray
  Damage: 6d6 magic (3d6 initial, 3d6 after one round)
  Special: Reduces target's armor class, THAC0 and damage by 1 point each time damage is dealt
  Range: 100 ft.
  Area of Effect: 1 creature

Requires:
 9 Intelligence

Weight: 1~

COPY ~%MOD_FOLDER%/itempack/c0sawan2.itm~ ~override~
SAY NAME1 ~Wand~
SAY NAME2 ~Wand of Life-Draining~
SAY UNIDENTIFIED_DESC ~Wands are 1 1/4 feet long and slender. They are made of ivory, bone, or wood and are usually tipped with something – metal, crystal, stone, etc. They are fragile and tend to break easily. Because of this, they are often kept in cases. Wands generally store one or more magical effects powered by charges, each use costing one or more charges (depending in the item). When a wand runs out of charges, it is consumed and destroyed.~
SAY DESC ~This wand was created using Shadow Magic and, unlike other items enchanted by the same source, may be used by any user of arcane magic. When used, this wand drains the vitality of its target and grants it to the wielder. However, it may not affect the same target again for one turn.

As this wand draws power from the Shadow Weave, anyone aside from a shadow adept who attempts to use this wand will suffer 1d10 magic damage.

STATISTICS:

Charge abilities:
– Drains four points of Constitution from target
  Range: 100 ft.
  Area of Effect: 1 creature

Requires:
 9 Intelligence

Weight: 1~

COPY ~%MOD_FOLDER%/itempack/c0sawan3.itm~ ~override~
SAY NAME1 ~Wand~
SAY NAME2 ~Wand of Nightshade~
SAY UNIDENTIFIED_DESC ~Wands are 1 1/4 feet long and slender. They are made of ivory, bone, or wood and are usually tipped with something – metal, crystal, stone, etc. They are fragile and tend to break easily. Because of this, they are often kept in cases. Wands generally store one or more magical effects powered by charges, each use costing one or more charges (depending in the item). When a wand runs out of charges, it is consumed and destroyed.~
SAY DESC ~This wand was created using Shadow Magic and, unlike other items enchanted by the same source, may be used by any user of arcane magic. When used, this wand fires a bolt of energy that shreds the target's life force, dealing damage proportional to their health.

As this wand draws power from the Shadow Weave, anyone aside from a shadow adept who attempts to use this wand will suffer 1d10 magic damage.

STATISTICS:

Charge abilities:
– Deals 30% of target's maximum hit points in magic damage (Save vs. Wand for half)
  Range: 100 ft.
  Area of Effect: 1 creature

Requires:
 9 Intelligence

Weight: 1~

COPY ~%MOD_FOLDER%/itempack/c0sawan4.itm~ ~override~
SAY NAME1 ~Wand~
SAY NAME2 ~Wand of Shadow Missiles~
SAY UNIDENTIFIED_DESC ~Wands are 1 1/4 feet long and slender. They are made of ivory, bone, or wood and are usually tipped with something – metal, crystal, stone, etc. They are fragile and tend to break easily. Because of this, they are often kept in cases. Wands generally store one or more magical effects powered by charges, each use costing one or more charges (depending in the item). When a wand runs out of charges, it is consumed and destroyed.~
SAY DESC ~This wand was created using Shadow Magic and, unlike other items enchanted by the same source, may be used by any user of moderate intelligence. When used, this wand launches five icy missiles that deal damage to the target.

As this wand draws power from the Shadow Weave, anyone aside from a shadow adept who attempts to use this wand will suffer 1d10 magic damage.

STATISTICS:

Charge abilities:
– 5 Shadow Missiles will strike the target
  Damage: 1d4 magic damage, 1 cold damage per missile
  Special: Each missile penalizes target's THAC0 by one point
  Range: 100 ft.
  Area of Effect: 1 creature

Requires:
 9 Intelligence

Weight: 1~

ADD_PROJECTILE ~%MOD_FOLDER%/spells/c0proj05.pro~

COPY ~%MOD_FOLDER%/itempack/c0sawan5.itm~ ~override~
  LPF ALTER_ITEM_HEADER
	INT_VAR
	header = 1
	projectile = c0proj05
END
SAY NAME1 ~Wand~
SAY NAME2 ~Wand of Shadow Fire~
SAY UNIDENTIFIED_DESC ~Wands are 1 1/4 feet long and slender. They are made of ivory, bone, or wood and are usually tipped with something – metal, crystal, stone, etc. They are fragile and tend to break easily. Because of this, they are often kept in cases. Wands generally store one or more magical effects powered by charges, each use costing one or more charges (depending in the item). When a wand runs out of charges, it is consumed and destroyed.~
SAY DESC ~This wand was created using Shadow Magic and, unlike other items enchanted by the same source, may be used by any user of moderate intelligence. This wand is capable of manipulating magical fire from the Plane of Shadow, launching either a large blast or arrows of flame according to the user's choice.

As this wand draws power from the Shadow Weave, anyone aside from a shadow adept who attempts to use this wand will suffer 1d10 magic damage.

STATISTICS:

Charge abilities:
– Shadowblast
  Damage: 3d6 cold, 3d6 magic (Save vs. Wand to avoid magic damage)
  Special: Reduces saving throws and attack rolls by one point (Save vs. Wand to avoid)
  Range: 90 ft.
  Area of Effect: 30-ft. radius 

– 3 Blackfire Arrows
  Damage: 1d6 cold, 4d6 fire per arrow (Save vs. Wand for half)
  Range: 90 ft.
  Area of Effect: 1 creature

Requires:
 9 Intelligence

Weight: 1~

COPY ~%MOD_FOLDER%/itempack/c0sawan6.itm~ ~override~
SAY NAME1 ~Wand~
SAY NAME2 ~Wand of Shadow Binding~
SAY UNIDENTIFIED_DESC ~Wands are 1 1/4 feet long and slender. They are made of ivory, bone, or wood and are usually tipped with something – metal, crystal, stone, etc. They are fragile and tend to break easily. Because of this, they are often kept in cases. Wands generally store one or more magical effects powered by charges, each use costing one or more charges (depending in the item). When a wand runs out of charges, it is consumed and destroyed.~
SAY DESC ~This wand was created using Shadow Magic and, unlike other items enchanted by the same source, may be used by any user of moderate intelligence. This wand is capable of creating shadowy tendrils which bind themselves around the chosen target, holding them in place.

As this wand draws power from the Shadow Weave, anyone aside from a shadow adept who attempts to use this wand will suffer 1d10 magic damage.

STATISTICS:

Charge abilities:
– Targets must save vs. spells at -4 or become held for one turn
  Range: 35 ft.
  Area of Effect: 1 creature and any enemy within 7.5 ft.

Requires:
 9 Intelligence

Weight: 1~

COPY ~%MOD_FOLDER%/itempack/c0sabo1a.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sabo1b.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0saboo1.itm~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 177 // display string
      match_parameter1 = 0
 parameter1 = 12
 parameter2 = 6
  END
SAY NAME1 ~Boots~
SAY NAME2 ~Night Treads~
SAY UNIDENTIFIED_DESC ~Boots are normally hand-made by cobblers. Common boots are made by using a form, but good boots are designed for the foot of an individual.~
SAY DESC ~These boots seem to be crafted of sturdy material yet weigh almost nothing. Their enchantments grant the wearer greater agility and speed as well as the ability to walk between planes, walking from the Prime Material Plane into the Plane of Shadow in a single step. This ability is limited, however, though the other powers of these boots remain persistent.

STATISTICS:

Charge abilities (five charges):
– Shadowstep

Equipped abilities:
– Dexterity: +2 (Shadow Adepts), +1 (Others)
– Movement Rate: +2 (Shadow Adepts)

Weight: 1~

COPY ~%MOD_FOLDER%/itempack/c0sabel1.spl~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sabel1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Belt~
SAY NAME2 ~Belt of Darkflame~
SAY DESC ~Girdles are generally similar to belts. Unlike belts, girdles are not used to hold up pants and dungarees, but to carry pouches, scabbards, and the like. 

STATISTICS:

Weight: 2~
SAY DESC ~Kryn Darkflame, in his younger days, experimented tirelessly in an attempt to draw more power from the Shadow Weave. The creation of this belt was an indicator of some success, as wearing it causes a shadow adept's powers to increase dramatically. However, as all things have their disadvantages, the wearer will find themselves more susceptible to the draining effects of Shadow Magic. Darkflame's magic eventually became great enough that he no longer required the belt's power and its effects became more of a hindrance, but to one less experienced in wielding the Shadow Weave it is a valuable item... so long as one can live with the added risk.

STATISTICS:

Equipped abilities:
– Caster Level: +2 (+4 when below 50% hit points)
– Fire Resistance: +40%
– Cold Resistance: +40%
– Save vs. Death: -4
– Hit Points: -15
– May cast one additional wizard spell of each level
– May only be removed with a Remove Curse spell

Weight: 2~

COPY ~%MOD_FOLDER%/itempack/c0sasta2.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Quarterstaff~
SAY NAME2 ~Shadowstone Staff +2~
SAY DESC ~The simplest of staff weapons is the quarterstaff, a length of wood six to nine feet in length. High quality quarterstaves are made of stout oak and are shod with metal at both ends. Powerful enchantments during the making of this staff have improved its accuracy and the damage it can cause, but they bear no signature.

This enchanted staff is topped with a shadow gem, bestowing upon it powers from the Plane of Shadow but restricting it to those proficient in its brand of magic.

STATISTICS:

Combat abilities:
– 50% chance to deal 2d6 magic damage and silence for 2 rounds on a failed save vs. spell

Equipped effects:
– Intelligence: +1
– Armor Class: +2 vs. good creatures

THAC0: +2
Damage: 1d6+2 (crushing)
Speed Factor: 2
Proficiency Type: Quarterstaff
Type: Two-handed
Requires:
 5 Strength

Weight: 3~

COPY ~%MOD_FOLDER%/itempack/c0sarob2.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Mage Robe~
SAY NAME2 ~Robe of the Shadow Magi~
SAY DESC ~This powerful mage robe offers protection from all forms of physical attack while at the same time increasing one's resistance to magic and the life-draining effects of Shadow Magic. Due to the nature of its enchantment, it can only be worn by Shadow Adepts.

STATISTICS:

Equipped abilities:
– Armor Class: 5
– Magic Resistance: +5%
– Protects against Constitution loss from 1st and 2nd level Shadow Weave spells

Weight: 6~

COPY ~%MOD_FOLDER%/itempack/c0saiou1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Ioun Stone~
SAY NAME2 ~Ioun of Sacred Darkness~
SAY DESC ~This ioun stone has a dark-colored hue. When worn, the stone regenerates its bearer's wounds and provides them with greater clarity.

STATISTICS:

Equipped abilities:
– Regenerate 1 hit point every 12 seconds
– Wisdom: +1

Weight: 0~

COPY ~%MOD_FOLDER%/itempack/c0samis1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Candlestick~
SAY NAME2 ~Soulflare Candle~
SAY DESC ~This candle emanates a powerful magical presence. Only a shadow adept may light it, and upon being lit, it gives off a ghostly flame which can be manipulated to replicate powerful Shadow Weave magic. However, lighting the candle is draining on the shadow adept's life force and can only be done a limited number of times per day.

STATISTICS:

Charge abilities (once per day):
– May cast Unmask and Breaching Dark at the cost of ten hit points

Weight: 3~

COPY ~%MOD_FOLDER%/itempack/c0samis2.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Nightsinger~)
END
SAY NAME1 ~Lute~
SAY NAME2 ~Lute of Lifedraining~
SAY DESC ~This sinister lute makes unpleasant sounds when strummed, causing a chill to go down the spines who hear its notes. When played by one skilled in Shadow Magic, its magic allows its user to drain the life force of others.

STATISTICS:

Charge abilities (three times per day):
– Mass Lesser Drain Vitality
  Range: Self
  Area of Effect: 30'

Weight: 3~

COPY ~%MOD_FOLDER%/itempack/c0sacha1.itm~ ~override/chan09.itm~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Chain Mail~
SAY NAME2 ~Darkmail +3~
SAY DESC ~A chain mail tunic fashioned from some sort of bright metal. It is always worn over a layer of padded fabric or soft leather to prevent chafing and lessen the impact of blows.

STATISTICS:

Armor Class: 5 (3 vs. slashing, 7 vs. crushing)
Requires:
 8 Strength

Weight: 5~
SAY DESC ~This suit of dark-colored chain mail is surprisingly light and somehow makes no sound, despite being composed of countless metal links. Having been worn by inhabitants of the Shadow Plane, it appears to have taken on some of its previous owner's power, giving it magical properties. Those who wear this armor find their forms shrouded in a protective veil of shadow.

STATISTICS:

Equipped abilities:
– Save vs. Death: +2
– Immunity to level drain
– Spellcasting is not disabled
– All magic damage inflicted by the wearer is increased by 15%

Armor Class: 2 (0 vs. slashing, 4 vs. crushing)
Requires:
 8 Strength

Weight: 5~

COPY ~%MOD_FOLDER%/itempack/c0samas1.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0samas2.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0samas3.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0samask.itm~ ~override~
SAY NAME1 ~Mask~
SAY NAME2 ~Eyes of the Void~
SAY DESC ~This ornate mask resonates with power, as it contains a powerful enchantment that allows it to shield its wearer's mind from magical intrusion. The symbol of Shar is carved upon its center.

STATISTICS:

Equipped abilities:
– Intelligence, Wisdom, Charisma: +1 (Sharrans)
– Immunity to blindness, charm, confusion, domination, and hold

Weight: 1~

COPY ~%MOD_FOLDER%/itempack/c0sanos1.spl~ ~override~
COPY ~%MOD_FOLDER%/itempack/c0sanos1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept~)
END
SAY NAME1 ~Spellbook~
SAY NAME2 ~Nosferatu~
SAY DESC ~This heavy spellbook emanates a malignant aura, making it uncomfortable even to hold.

STATISTICS:

Weight: 4~
SAY DESC ~This heavy spellbook emanates a malignant aura, making it uncomfortable even to hold. When held in one's hand, it serves as an amplifier for shadow magic, and allows one to channel pure shadow energy in the form of powerful life-draining blasts.

STATISTICS:

Combat abilities:
– Drain 3d6+2 hit points from the target and transfers it to the wielder (40 charges)
– Upon killing a target, regain one spell of up to 6th level

Equipped abilities:
– May only be removed with a Remove Curse spell
– May cast one bonus spell of each level
– Hit Points: -40
– Caster Level: +2 
– Casting Speed: +1
– Attacks per round set to 1

STATISTICS:

THAC0: +6
Damage: 3d6+2 (magic)
Speed Factor: 2
Proficiency Type: None
Type: One-handed

Weight: 4~

ACTION_IF FILE_EXISTS_IN_GAME ~demilich.cre~ THEN BEGIN
COPY_EXISTING ~demilich.cre~ ~override~
ADD_CRE_ITEM ~c0sanos1~ #0 #0 #0 ~NONE~ ~inv~
END

COPY ~%MOD_FOLDER%/itempack/leat19a.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/leat19b.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/leat19c.eff~ ~override~
COPY ~%MOD_FOLDER%/itempack/leat19.itm~ ~override~
SAY DESC ~This suit of armor is formed from interlocking shadow dragon scales. Elegant workmanship and practical considerations make this armor both beautiful and useful. The shadow dragon scales grant the wearer immunity to level drain, but while worn by a shadow adept, it greatly empowers them, allowing them to use their magic with less risk.

STATISTICS:

Equipped abilities:
– Immunity to level drain
– Spellcasting is not disabled (Shadow Adepts)
– Save vs. Death: +4 (Shadow Adepts), +2 (Others)
– Maximum Hit Points: +20% (Shadow Adepts)

Armor Class: 1 (-1 vs. slashing, 0 vs. piercing and missile)
Requires:
 6 Strength

Weight: 10~

COMPILE ~%MOD_FOLDER%/dialogue/c0sascrl.d~

OUTER_SET readscroll = RESOLVE_STR_REF (~Read Scroll~)
APPEND ~ITEMDIAL.2da~ ~C0SASCR1    %readscroll%    C0SASCR1
C0SASCR2    %readscroll%    C0SASCR2
C0SASCR3    %readscroll%    C0SASCR3
C0SASCR4    %readscroll%    C0SASCR4
C0SASCR5    %readscroll%    C0SASCR5
C0SASCR6    %readscroll%    C0SASCR6
C0SASCR7    %readscroll%    C0SASCR7
C0SASCR8    %readscroll%    C0SASCR8
C0SASCR9    %readscroll%    C0SASCR9~

COPY ~%MOD_FOLDER%/itempack/c0sascr1.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept (not Shadow Disciple)~)
END
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 19
	  parameter2 = 5
	  power = 0
END
SAY NAME1 ~Scroll~
SAY NAME2 ~Shadow Scroll I~
SAY DESC ~This spell scroll contains incantations that would be indecipherable to anyone not versed in the art of Shadow Magic. Upon studying it, a shadow adept may learn an extra spell at the expense of the scroll.

STATISTICS:

Special: Learn one 1st level Shadow Weave spell.

Weight: 0~

COPY ~%MOD_FOLDER%/itempack/c0sascr2.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept (not Shadow Disciple)~)
END
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 19
	  parameter2 = 5
	  power = 0
END
SAY NAME1 ~Scroll~
SAY NAME2 ~Shadow Scroll II~
SAY DESC ~This spell scroll contains incantations that would be indecipherable to anyone not versed in the art of Shadow Magic. Upon studying it, a shadow adept may learn an extra spell at the expense of the scroll.

STATISTICS:

Special: Learn one 2nd level Shadow Weave spell.

Weight: 0~

COPY ~%MOD_FOLDER%/itempack/c0sascr3.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept (not Shadow Disciple)~)
END
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 19
	  parameter2 = 5
	  power = 0
END
SAY NAME1 ~Scroll~
SAY NAME2 ~Shadow Scroll III~
SAY DESC ~This spell scroll contains incantations that would be indecipherable to anyone not versed in the art of Shadow Magic. Upon studying it, a shadow adept may learn an extra spell at the expense of the scroll.

STATISTICS:

Special: Learn one 3rd level Shadow Weave spell.

Weight: 0~

COPY ~%MOD_FOLDER%/itempack/c0sascr4.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept (not Shadow Disciple)~)
END
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 19
	  parameter2 = 5
	  power = 0
END
SAY NAME1 ~Scroll~
SAY NAME2 ~Shadow Scroll IV~
SAY DESC ~This spell scroll contains incantations that would be indecipherable to anyone not versed in the art of Shadow Magic. Upon studying it, a shadow adept may learn an extra spell at the expense of the scroll.

STATISTICS:

Special: Learn one 4th level Shadow Weave spell.

Weight: 0~

COPY ~%MOD_FOLDER%/itempack/c0sascr5.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept (not Shadow Disciple)~)
END
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 19
	  parameter2 = 5
	  power = 0
END
SAY NAME1 ~Scroll~
SAY NAME2 ~Shadow Scroll V~
SAY DESC ~This spell scroll contains incantations that would be indecipherable to anyone not versed in the art of Shadow Magic. Upon studying it, a shadow adept may learn an extra spell at the expense of the scroll.

STATISTICS:

Special: Learn one 5th level Shadow Weave spell.

Weight: 0~

COPY ~%MOD_FOLDER%/itempack/c0sascr6.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept (not Shadow Disciple)~)
END
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 19
	  parameter2 = 5
	  power = 0
END
SAY NAME1 ~Scroll~
SAY NAME2 ~Shadow Scroll VI~
SAY DESC ~This spell scroll contains incantations that would be indecipherable to anyone not versed in the art of Shadow Magic. Upon studying it, a shadow adept may learn an extra spell at the expense of the scroll.

STATISTICS:

Special: Learn one 6th level Shadow Weave spell.

Weight: 0~

COPY ~%MOD_FOLDER%/itempack/c0sascr7.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept (not Shadow Disciple)~)
END
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 19
	  parameter2 = 5
	  power = 0
END
SAY NAME1 ~Scroll~
SAY NAME2 ~Shadow Scroll VII~
SAY DESC ~This spell scroll contains incantations that would be indecipherable to anyone not versed in the art of Shadow Magic. Upon studying it, a shadow adept may learn an extra spell at the expense of the scroll.

STATISTICS:

Special: Learn one 7th level Shadow Weave spell.

Weight: 0~

COPY ~%MOD_FOLDER%/itempack/c0sascr8.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept (not Shadow Disciple)~)
END
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 19
	  parameter2 = 5
	  power = 0
END
SAY NAME1 ~Scroll~
SAY NAME2 ~Shadow Scroll VIII~
SAY DESC ~This spell scroll contains incantations that would be indecipherable to anyone not versed in the art of Shadow Magic. Upon studying it, a shadow adept may learn an extra spell at the expense of the scroll.

STATISTICS:

Special: Learn one 8th level Shadow Weave spell.

Weight: 0~

COPY ~%MOD_FOLDER%/itempack/c0sascr9.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 12
	  parameter2 = 6
	  power = 1
	  special = RESOLVE_STR_REF (~Shadow Adept (not Shadow Disciple)~)
END
  LPF ADD_ITEM_EQEFFECT
    INT_VAR
      opcode = 319
	  target = 1
	  timing = 2
	  parameter1 = 19
	  parameter2 = 5
	  power = 0
END
SAY NAME1 ~Scroll~
SAY NAME2 ~Shadow Scroll IX~
SAY DESC ~This spell scroll contains incantations that would be indecipherable to anyone not versed in the art of Shadow Magic. Upon studying it, a shadow adept may learn an extra spell at the expense of the scroll.

STATISTICS:

Special: Learn one 9th level Shadow Weave spell.

Weight: 0~
