COPY ~%MOD_FOLDER%/SPELLS/C0SA101.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA102.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA103.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA104.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA105.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA106.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA108.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA111.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA112.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA202.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA204.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA205.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA207.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA208.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA209.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA210.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA212.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA301.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA302.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA303.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA304.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA305.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA307.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA308.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA310.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA312a.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA401a.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA403.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA406.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA407.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA408.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA410.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA411.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA412a.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA501.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA503.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA505.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA506.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA508.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA509.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA510.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA604.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA605.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA606.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA607A.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA608.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA609.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA610.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA611A.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA701.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA702.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA703.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA705B.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA706.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA708.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA709.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA710.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA714.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA801.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA803.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA804.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA806.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA807B.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA812.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA814A.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA815.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA901.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA903.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA904A.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA906.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA907.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA907A.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA908A.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SA909.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END
COPY ~%MOD_FOLDER%/SPELLS/C0SAHLA2.SPL~ ~OVERRIDE/MOD~
	LPF ADD_SPELL_EFFECT
		INT_VAR
		opcode = 146
		target = 2
		timing = 1
		parameter2 = 1
		STR_VAR
		resource = C0SARN4C
	END