ACTION_DEFINE_ASSOCIATIVE_ARRAY sa_anims_7xxx BEGIN
    ~C0MG~ => ~C0_Shadow_Magi~
    ~C0ME~ => ~C0_Shadow_Mephit~
  END
  ACTION_PHP_EACH sa_anims_7xxx AS sa_folder => symbol BEGIN
    ACTION_BASH_FOR ~%MOD_FOLDER%/animations/%sa_folder%~ ~.+\.bam~ ~%MOD_FOLDER%/animations/%sa_folder%~ ~.+\.bmp~ BEGIN
      COPY ~%BASH_FOR_FILESPEC%~ ~override~
    END
    LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x7000 RET slot END
    LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
    COPY ~%MOD_FOLDER%/animations/%sa_folder%/7xxx.ini~ ~override/%hexNumber%.ini~
    OUTER_SET EVAL ~slot_%sa_folder%~ = slot   // save animation slot number for later
    APPEND ~ANIMATE.IDS~ ~0x%hexNumber% %symbol%~
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY sa_anims_Exxx BEGIN
    ~C0NW~ => ~C0_Nightwalker~
    ~C0WO~ => ~C0_Shadow_Wolf~
    ~C0CH~ => ~C0_Shadow_Chimera~
    ~C0HD~ => ~C0_Half_Dragon_Shadow~
    ~C0NH~ => ~C0_Nighthaunt~
    ~C0SH1~ => ~C0_Shadow~
    ~C0SH2~ => ~C0_Shadow_Large~
  END
  ACTION_PHP_EACH sa_anims_Exxx AS sa_folder => symbol BEGIN
    ACTION_BASH_FOR ~%MOD_FOLDER%/animations/%sa_folder%~ ~.+\.bam~ ~%MOD_FOLDER%/animations/%sa_folder%~ ~.+\.bmp~ BEGIN
      COPY ~%BASH_FOR_FILESPEC%~ ~override~
    END
    LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 RET slot END
    LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
    COPY ~%MOD_FOLDER%/animations/%sa_folder%/Exxx.ini~ ~override/%hexNumber%.ini~
    OUTER_SET EVAL ~slot_%sa_folder%~ = slot   // save animation slot number for later
    APPEND ~ANIMATE.IDS~ ~0x%hexNumber% %symbol%~
END
