
IF
  Global("C0JevanShop","Global",0)
  Specifics([PC],SHADOW_ADEPT)
  OR(2)
  Global("RefusedQilueBrain","GLOBAL",1)
  Global("GetQilueBrain","GLOBAL",1)
THEN
  RESPONSE #100
    StartDialogueNoSet(Player1)
END

IF
  Global("C0SAJevanSpawn","GLOBAL",1)
  Global("DrowCityHostile","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("C0SAJevanSpawn","GLOBAL",-1)
    ForceSpell(Myself,DRYAD_TELEPORT)
END