// Shadow Gate

IF
  Die()
THEN
  RESPONSE #100
    CreateVisualEffectObject("c0magich",Myself)
END

IF
	!Global("ShadowGate","LOCALS",1)
THEN
  RESPONSE #100
	SetGlobal("ShadowGate","LOCALS",1)
	RealSetGlobalTimer("SpawnShadow","LOCALS",6)
	Continue()
END

IF
	RealGlobalTimerExpired("SpawnShadow","LOCALS")
	Global("ShadowGate","LOCALS",1)
THEN
  RESPONSE #100
	ApplySpellRES("c0sa711a",Myself)
	RealSetGlobalTimer("SpawnShadow","LOCALS",6)
	Continue()
END