// Nightsinger's Tithe

IF
  GlobalGT("C0SA903","LOCALS",49)
  Global("C0NightsingerTithe","LOCALS",0)
THEN
  RESPONSE #100
	SetGlobal("C0NightsingerTithe","LOCALS",1)
	ApplySpellRES("C0SA903B",Myself)
	Continue()
END

IF
	!InParty(Myself)
	Specifics(Myself,12)
	Global("C0NoSpellDuplicates","LOCALS",0)
THEN
  RESPONSE #100
	SetGlobal("C0NoSpellDuplicates","LOCALS",1)
	ApplySpellRES("c0sansd",Myself)
END